# golangci-lint configuration
version: 2
run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - goconst
    - gocritic
    - gocyclo
    - nolintlint
    - unconvert
    - unparam
    - whitespace
  disable:
    - errcheck
    - bodyclose
    - gosec
    - goconst
    - nolintlint
    - revive

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 5

  misspell:
    locale: US

  revive:
    confidence: 0.8

  gosec:
    excludes:
      - G104  # Errors unhandled
      - G204  # Subprocess launched with variable
      - G302  # File permissions
      - G304  # File inclusion via variable

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - ".*_test\\.go$"
  exclude-rules:
    - path: examples/
      linters:
        - errcheck
        - unparam