name: Extract PR Context
description: Safely extract PR details including title, body, changed files, and author information
inputs:
  pr_number:
    description: Pull request number to extract context from
    required: true
  github_token:
    description: GitHub token for API access
    required: true
outputs:
  pr_number:
    description: The PR number
    value: ${{ steps.extract.outputs.pr_number }}
  pr_title:
    description: The PR title
    value: ${{ steps.extract.outputs.pr_title }}
  pr_body:
    description: The PR body/description
    value: ${{ steps.extract.outputs.pr_body }}
  pr_author:
    description: The PR author username
    value: ${{ steps.extract.outputs.pr_author }}
  head_ref:
    description: The PR head branch name
    value: ${{ steps.extract.outputs.head_ref }}
  changed_files:
    description: Comma-separated list of changed file paths
    value: ${{ steps.extract.outputs.changed_files }}

runs:
  using: composite
  steps:
    - name: Extract PR Context
      id: extract
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ inputs.pr_number }}
          });
          
          // Get changed files
          const files = await github.rest.pulls.listFiles({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: ${{ inputs.pr_number }}
          });
          const changedFiles = files.data.map(f => f.filename).join(',');
          
          // Set outputs
          core.setOutput('pr_number', pr.data.number);
          core.setOutput('pr_title', pr.data.title);
          core.setOutput('pr_body', pr.data.body || '');
          core.setOutput('pr_author', pr.data.user.login);
          core.setOutput('head_ref', pr.data.head.ref);
          core.setOutput('changed_files', changedFiles);
