name: Generate Forge Configuration
description: Generate a Forge configuration file for documentation or code tasks
inputs:
  task_description:
    description: The main task description for Forge
    required: true
  pr_title:
    description: Pull request title
    required: false
  pr_body:
    description: Pull request body/description
    required: false
  changed_files:
    description: Comma-separated list of changed files
    required: false
  custom_instructions:
    description: Additional custom instructions to append
    required: false
  
  # Workspace settings
  workspace_dir:
    description: Workspace directory path
    required: false
    default: "."
  mode:
    description: Operation mode (read-only or write)
    required: false
    default: "write"
  
  # File constraints
  file_patterns:
    description: Comma-separated glob patterns for allowed files
    required: false
    default: "**/*"
  deny_patterns:
    description: Comma-separated glob patterns for denied files
    required: false
    default: "node_modules/**,vendor/**,.git/**"
  
  # Tool constraints
  allowed_tools:
    description: Comma-separated list of allowed tools
    required: false
    default: "read_file,list_files,search_files,execute_command,write_file,apply_diff,add_note,list_notes,search_notes,list_tags,scratch_note,update_note"
  
  # Resource constraints
  max_tokens:
    description: Maximum tokens for the task
    required: false
    default: "1000000"
  max_files:
    description: Maximum number of files to modify (write mode only)
    required: false
    default: "50"
  max_lines_changed:
    description: Maximum total lines that can be changed (write mode only)
    required: false
    default: "2000"
  timeout:
    description: Task timeout duration
    required: false
    default: "10m"
  
  # Artifacts settings
  artifacts_enabled:
    description: Enable artifact generation
    required: false
    default: "true"
  artifacts_output_dir:
    description: Artifact output directory
    required: false
    default: ".forge/artifacts"
  artifacts_json:
    description: Generate JSON artifacts
    required: false
    default: "true"
  artifacts_markdown:
    description: Generate markdown artifacts
    required: false
    default: "true"
  artifacts_metrics:
    description: Generate metrics artifacts
    required: false
    default: "true"
  
  # Git settings
  git_mode:
    description: Git operation mode (pr, direct, or none)
    required: false
    default: "none"
  git_branch:
    description: Git branch name (for pr mode)
    required: false
  git_commit_message:
    description: Git commit message
    required: false
  git_pr_title:
    description: PR title (for pr mode)
    required: false
  git_pr_body:
    description: PR body (for pr mode)
    required: false
  git_pr_draft:
    description: Create PR as draft
    required: false
    default: "false"
  
  # Quality gates settings
  quality_gates:
    description: JSON array of quality gate commands to run
    required: false
    default: '[]'
outputs:
  config_path:
    description: Path to the generated configuration file
    value: ${{ steps.generate.outputs.config_path }}

runs:
  using: composite
  steps:
    - name: Generate Configuration
      id: generate
      shell: bash
      run: |
        # Write inputs to temp files to avoid shell quoting issues
        cat > /tmp/task_desc.txt <<'EOF'
        ${{ inputs.task_description }}
        EOF

        if [ -n "${{ inputs.pr_title }}" ]; then
          cat > /tmp/pr_title.txt <<'EOF'
        ${{ inputs.pr_title }}
        EOF
        fi

        if [ -n "${{ inputs.pr_body }}" ]; then
          cat > /tmp/pr_body.txt <<'EOF'
        ${{ inputs.pr_body }}
        EOF
        fi

        if [ -n "${{ inputs.changed_files }}" ]; then
          cat > /tmp/changed_files.txt <<'EOF'
        ${{ inputs.changed_files }}
        EOF
        fi

        # Build task instructions
        cat /tmp/task_desc.txt > /tmp/instructions.txt

        # Add PR context if provided
        if [ -f /tmp/pr_title.txt ]; then
          echo "" >> /tmp/instructions.txt
          echo "" >> /tmp/instructions.txt
          echo "PR Title: " >> /tmp/instructions.txt
          cat /tmp/pr_title.txt >> /tmp/instructions.txt
        fi

        if [ -f /tmp/pr_body.txt ]; then
          echo "" >> /tmp/instructions.txt
          echo "" >> /tmp/instructions.txt
          echo "PR Description:" >> /tmp/instructions.txt
          cat /tmp/pr_body.txt >> /tmp/instructions.txt
        fi

        if [ -f /tmp/changed_files.txt ]; then
          echo "" >> /tmp/instructions.txt
          echo "" >> /tmp/instructions.txt
          echo "Changed Files: $(cat /tmp/changed_files.txt)" >> /tmp/instructions.txt
        fi

        # Add custom instructions if provided
        if [ -n "${{ inputs.custom_instructions }}" ]; then
          echo "" >> /tmp/instructions.txt
          echo "" >> /tmp/instructions.txt
          echo "Additional Instructions:" >> /tmp/instructions.txt
          cat >> /tmp/instructions.txt <<'EOF'
        ${{ inputs.custom_instructions }}
        EOF
        fi

        # Read final instructions
        INSTRUCTIONS=$(cat /tmp/instructions.txt)

        # Build file allow/deny lists
        IFS=',' read -ra ALLOW_PATTERNS <<< "${{ inputs.file_patterns }}"
        IFS=',' read -ra DENY_PATTERNS <<< "${{ inputs.deny_patterns }}"
        IFS=',' read -ra ALLOWED_TOOLS <<< "${{ inputs.allowed_tools }}"

        ALLOW_JSON=$(printf '%s\n' "${ALLOW_PATTERNS[@]}" | jq -R . | jq -s .)
        DENY_JSON=$(printf '%s\n' "${DENY_PATTERNS[@]}" | jq -R . | jq -s .)
        TOOLS_JSON=$(printf '%s\n' "${ALLOWED_TOOLS[@]}" | jq -R . | jq -s .)

        # Generate config using jq for proper JSON encoding
        TASK_JSON=$(printf '%s' "$INSTRUCTIONS" | jq -R -s .)

        # Build base config
        jq -n \
          --argjson task "$TASK_JSON" \
          --arg mode "${{ inputs.mode }}" \
          --arg workspace "${{ inputs.workspace_dir }}" \
          --argjson allow "$ALLOW_JSON" \
          --argjson deny "$DENY_JSON" \
          --argjson tools "$TOOLS_JSON" \
          --argjson max_tokens "${{ inputs.max_tokens }}" \
          --argjson max_files "${{ inputs.max_files }}" \
          --argjson max_lines "${{ inputs.max_lines_changed }}" \
          --arg timeout "${{ inputs.timeout }}" \
          --argjson artifacts_enabled "${{ inputs.artifacts_enabled }}" \
          --arg artifacts_dir "${{ inputs.artifacts_output_dir }}" \
          --argjson artifacts_json "${{ inputs.artifacts_json }}" \
          --argjson artifacts_md "${{ inputs.artifacts_markdown }}" \
          --argjson artifacts_metrics "${{ inputs.artifacts_metrics }}" \
          '{
          "task": $task,
          "mode": $mode,
          "workspace_dir": $workspace,
          "constraints": {
            "allowed_patterns": $allow,
            "denied_patterns": $deny,
            "allowed_tools": $tools,
            "max_tokens": $max_tokens,
            "timeout": $timeout
          },
          "artifacts": {
            "enabled": $artifacts_enabled,
            "output_dir": $artifacts_dir,
            "json": $artifacts_json,
            "markdown": $artifacts_md,
            "metrics": $artifacts_metrics
          }
        }' > /tmp/base_config.json

        # Add write mode constraints if mode is write
        if [ "${{ inputs.mode }}" = "write" ]; then
          jq --argjson max_files "${{ inputs.max_files }}" \
             --argjson max_lines "${{ inputs.max_lines_changed }}" \
             '.constraints.max_files = $max_files | .constraints.max_lines_changed = $max_lines' \
             /tmp/base_config.json > /tmp/config_with_write.json
          mv /tmp/config_with_write.json /tmp/base_config.json
        fi

        # Add quality gates if provided
        QUALITY_GATES='${{ inputs.quality_gates }}'
        if [ "$QUALITY_GATES" != "[]" ] && [ -n "$QUALITY_GATES" ]; then
          # Parse and add quality gates to config
          # Transform input array to add required: true by default
          GATES_WITH_REQUIRED=$(echo "$QUALITY_GATES" | jq -c 'map({
            name: .name,
            command: .command,
            required: true
          })')
          
          jq --argjson gates "$GATES_WITH_REQUIRED" \
             '.quality_gates = $gates' /tmp/base_config.json > /tmp/config_with_gates.json
          mv /tmp/config_with_gates.json /tmp/base_config.json
        fi

        # Add git configuration based on git_mode
        GIT_MODE="${{ inputs.git_mode }}"
        case "$GIT_MODE" in
          "pr")
            jq --arg branch "${{ inputs.git_branch }}" \
               --arg commit_msg "${{ inputs.git_commit_message }}" \
               --arg pr_title "${{ inputs.git_pr_title }}" \
               --arg pr_body "${{ inputs.git_pr_body }}" \
               --argjson pr_draft "${{ inputs.git_pr_draft }}" \
               '.git = {
                 "auto_commit": true,
                 "auto_push": true,
                 "create_pr": true,
                 "commit_on_quality_fail": true,
                 "branch": $branch,
                 "commit_message": $commit_msg,
                 "pr_title": $pr_title,
                 "pr_body": $pr_body,
                 "pr_draft": $pr_draft
               }' /tmp/base_config.json > forge-config.json
            ;;
          "direct")
            jq --arg commit_msg "${{ inputs.git_commit_message }}" \
               '.git = {
                 "auto_commit": true,
                 "auto_push": false,
                 "create_pr": false,
                 "commit_message": $commit_msg
               }' /tmp/base_config.json > forge-config.json
            ;;
          "none")
            cp /tmp/base_config.json forge-config.json
            ;;
          *)
            echo "::warning::Invalid git_mode '$GIT_MODE'. Supported modes are: pr, direct, none. Using 'none'."
            cp /tmp/base_config.json forge-config.json
            ;;
        esac

        # Clean up temp files
        rm -f /tmp/task_desc.txt /tmp/pr_title.txt /tmp/pr_body.txt /tmp/changed_files.txt /tmp/instructions.txt /tmp/base_config.json

        # Output config path
        echo "config_path=forge-config.json" >> $GITHUB_OUTPUT
