name: Run Forge
description: Execute Forge with a given configuration file
inputs:
  config_path:
    description: Path to the Forge configuration file
    required: true
  working_dir:
    description: Working directory for Forge execution
    required: false
    default: '.'
  openai_api_key:
    description: OpenAI API key (or compatible API key)
    required: true
  openai_base_url:
    description: OpenAI API base URL (for compatible APIs like OpenRouter)
    required: false
    default: ''
  model:
    description: LLM model to use (e.g., gpt-4, claude-3-5-sonnet-20241022, google/gemini-2.5-pro)
    required: false
    default: 'claude-3-5-sonnet-20241022'
outputs:
  exit_code:
    description: Exit code from Forge execution
    value: ${{ steps.run.outputs.exit_code }}
  artifacts_path:
    description: Path to artifacts directory if enabled
    value: ${{ steps.run.outputs.artifacts_path }}

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true

    - name: Install Forge
      shell: bash
      run: |
        # Check if forge is already installed
        if ! command -v forge &> /dev/null; then
          echo "Installing Forge..."
          go install github.com/entrhq/forge/cmd/forge@latest
        else
          echo "Forge already installed"
        fi

    - name: Run Forge
      id: run
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        # Verify config file exists
        if [ ! -f "${{ inputs.config_path }}" ]; then
          echo "Error: Config file not found at ${{ inputs.config_path }}"
          exit 1
        fi
        
        echo "Running Forge with config: ${{ inputs.config_path }}"
        cat "${{ inputs.config_path }}"
        
        # Build Forge command with optional model flag
        FORGE_CMD="forge --config \"${{ inputs.config_path }}\""
        
        if [ -n "${{ inputs.model }}" ]; then
          FORGE_CMD="$FORGE_CMD --model \"${{ inputs.model }}\""
        fi
        
        # Run Forge and capture exit code
        set +e
        eval $FORGE_CMD
        EXIT_CODE=$?
        set -e
        
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        
        # Check for artifacts directory
        if [ -d ".forge/artifacts" ]; then
          echo "artifacts_path=.forge/artifacts" >> $GITHUB_OUTPUT
        fi
        
        # Exit with Forge's exit code
        exit $EXIT_CODE
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        OPENAI_BASE_URL: ${{ inputs.openai_base_url }}

    - name: Upload Artifacts
      if: always() && steps.run.outputs.artifacts_path
      uses: actions/upload-artifact@v4
      with:
        name: forge-artifacts-${{ github.run_id }}
        path: ${{ steps.run.outputs.artifacts_path }}
        retention-days: 30
